/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bountyx merkle tree leaf data
 */
export interface BountyxMerkleLeafData {
  /**
   * Name of the bounty group, usually event name
   */
  group: string;
  /**
   * Name of the bounty
   */
  bountyName: string;
  /**
   * Bounty issuer public name
   */
  issuerName: string;
  /**
   * The address that eligible to receive or have received the bounty
   */
  receiverAddress: string;
  /**
   * Information about the reward
   */
  reward: {
    /**
     * Amount paid out by bounty issuer to the project in USD or token
     */
    rewardAmount: number;
    [k: string]: unknown;
  };
}
