/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Extension data for hypercert. Represents information about won bounties
 */
export interface BountyxMetadata {
  bounties: {
    /**
     * Name of the bounty
     */
    name?: string;
    /**
     * Description of the bounty
     */
    description?: string;
    /**
     * Issuer of the bounty
     */
    issuer?: {
      /**
       * Bounty issuer address
       */
      issuerAddress?: string;
      /**
       * Bounty issuer public name
       */
      issuerName?: string;
      /**
       * Bounty issuer logo url
       */
      issuerLogoUrl?: string;
      [k: string]: unknown;
    };
    /**
     * Information about the reward
     */
    reward?: {
      /**
       * Amount paid out by bounty issuer to the project
       */
      rewardAmountUsd?: number;
      [k: string]: unknown;
    };
    /**
     * Message to be signed by the bounty issuer to prove hypercert authenticity
     */
    endorsement?: string;
    /**
     * Signature of the bounty issuer endorsing the receiver
     */
    signature?: string;
    [k: string]: unknown;
  }[];
}
